apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: okeamazoc-go 
  janus-idp.io/tekton: okeamazoc-go
  backstage.io/kubernetes-id: okeamazoc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: okeamazoc-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  